### ISSUE TITLE
Name mixing

### ISSUE THREAD

**Issue by torwag** [asger-weirsoee/sway-smart-workspaces#1] opened 2021-06-02 15:16 UTC
I tried to use your solution, but I face challenges already in the naming scheme... The readme refers to pi3-sway-workspace but the package is named sway-smart-workspace and that is also what I find as a binary.

Calling sway-smart-workspace -i 1 I get a

FileNotFoundError: \[Errno 2\] No such file or directory: '/home/torsten/.local/lib/python3.9/site-packages/sway\_smart\_workspace/templates/output'

It also seems the links in pip point to  the wrong github repro.

**Comment by asger-weirsoee** [comment] 2021-06-02 15:45
Hey thanks for posting this as an issue as well.

As mentioned in the reddit post: I don't have time to look into this issue for the next 18 days, but the problem is that I didn't package the pypi repository correctly.

The work around is:

If you add them yourself to your output folder, then this exception wont occur.

You need a controls file, and for each of your outputs you need an output file, all located here:

https://github.com/asger-weirsoee/sway-smart-workspaces/blob/master/sway_smart_workspace/templates/

The naming of your outputs files must be the same name of your output, so if you have an output called DP-1 then you need to have an file called DP-1.

Inside the outputs file is two placeholders for variables, {index} and {name}.


{index} needs to be a number, the has to be unique to this outputs file, so lets say you have two outputs eDP-1 and DP-3.

{name} needs to be the name of the file (which should be the name of your output)

So lets say you have two outputs, eDP-1 and DP-3, then you need to have 3 files in your outputs folder:

controls ---> Just plain downloaded from the github repository

eDP-1 --> {name} should be eDP-1 and {index} could be 0

DP-3 --> {name} should be DP-3 and {index} could be 1


I'm sorry for the inconvenience

**Comment by torwag** [comment] 2021-06-03 18:28
I can confirm that your workaround works. 
Other things I noticed on the way to it, I will add into different issues to work on them.

**Comment by asger-weirsoee** [comment] 2021-07-11 19:33
This is fixed in release v0.1.1 by merging all of the required files into the "main" file.

**Closed as completed by asger-weirsoee** 2021-07-11 19:33 UTC
Labels: bug, documentation
